### ISSUE TITLE
min and max limits are rounded

### ISSUE THREAD

**Issue by PeterCervienka** [cicerono/validator#39]
If min and max limits contain float number, those numbers are rounded to lower integer during the validation.

example:
``` 
config: { integerOnly: false, min: 0, max: 9999999999.99 }
value: 9999999999.5

leads to 
result: numeric.max
```

It's because of calling `parseInt(9999999999.99)` what returns integer value `9999999999`. I suggest to use parseFloat instead of parseInt.

**Comment by relekang** [comment]
Closing as this was fixed in #40
